from build_chain import build_simple_chain_using_lcel

def is_response_valid(response: str) -> tuple[bool, list[str]]:
    """
    Validates whether the response generated follows the defined criteria or not. 

    Success Criterias:
    1. Response should be string.
    2. Response should not be empty.
    3. Response should contain exactly 3 bullet points.
    4. Response should not be too long (limit : 100 words)
    """

    # list of string
    errors = []

    if not isinstance(response, str):
        # response is not of string type.
        errors.append("Response is not string.")
        return False, errors
    
    # response shouldn't be empty
    if not response.strip():
        errors.append("Response is empty.")

    # Response should contain exactly 3 bullet points - Todo.

    word_count = len(response.split())

    if word_count > 10:
        errors.append("Response too long, more than 100 words)")
    
    return len(errors) == 0, errors
    # if len(errors) == 0:
    #     # no error
    #     return True, errors
    
    # return False, errors

chain = build_simple_chain_using_lcel()

test_case = {
    "topic" : "LCEL in Langchain",
    "analogy_domain" : "Software Engineering"
}

response = chain.invoke(test_case)

print(response)

# Validte the response.
is_valid, errors = is_response_valid(response)

if is_valid:
    print("Valid response")
else:
    print("Invalid response.")
    print(errors)

# LLM may not follow the exact instructions every time.
# That's why it becomes vey important to monitor & test the output generated by LLM constantly. 





